FROM python:3

RUN apt-get install --yes curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install --yes nodejs

RUN mkdir /opt/ellie/
COPY .env.example /opt/ellie/.env
ADD . /opt/ellie/

WORKDIR /opt/ellie/

RUN python3 -m venv ./env && . env/bin/activate
RUN pip install --no-cache-dir -r requirements.txt

RUN npm install

ENTRYPOINT ["flask", "run"]
