version: '2.1'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client

  minio:
    image: minio/minio
